### ISSUE TITLE
css如何实现一个自适应正方形

### ISSUE THREAD

**Issue by lxw124** [lxw124/Interview#104]

**Comment by lxw124** [comment]
①使用vw实现
```css
.square{
  width:10%;
  height:10vw;
  background-color:red;
  }
``
②利用元素的 margin/padding ,百分比是相对父元素 width 的性质来实现
```css
.square{ width:20%; 
height:0;
 padding-top:20%;
 background:orange; } 
```
③利用子元素的 margin-top 的值来实现
```css
.square{ width:30%; 
overflow:hidden;
 background:yellow; }
.square::after{ 
content:"";
 display:block; 
margin-top:100%; } 
```
