### ISSUE TITLE
css中0/50%是什么意思

### ISSUE THREAD

**Issue by lxw124** [lxw124/Interview#113]

**Comment by lxw124** [comment]
css的border-radius可以设置5个值，
例如
```css
.box{border-radius: 0 100% 100%  0/50%;}
```
可以转换成这四个值：
```css
.box{
border-radius-top-left:0 50%;
border-radius-top-right:100% 50%;
border-radius-bottom-right:100% 50%;
border-radius-bottom-left:0 50%;}
```
按此顺序设置每个 radii 的四个值。如果省略 bottom-left，则与 top-right 相同。如果省略 bottom-right，则与 top-left 相同。如果省略 top-right，则与 top-left 相同。
